workflows:
  native-android:
    name: Native Android
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - arifz.xyz
    scripts:
      - name: Build Android APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/**/outputs/apk/**/*.apk
    cache:
      cache_paths:
        - $HOME/.gradle/caches
    publishing:
      email:
        recipients:
          - arifantastic0@gmail.com